const assert = require('node:assert/strict');
const { execSync } = require('node:child_process');
const out = '/tmp/forest-tests';
execSync(`rm -rf ${out} && mkdir -p ${out} && tsc --ignoreConfig --target ES2020 --module commonjs --moduleResolution node --ignoreDeprecations 6.0 --esModuleInterop --skipLibCheck --outDir ${out} src/lib/voting.ts src/lib/scenarioValidation.ts src/data/defaultScenario.ts src/data/candidates.ts src/data/settings.ts src/types/game.ts`, { stdio: 'inherit' });
const { candidates, studentTeamCandidates } = require(`${out}/data/candidates.js`);
const { defaultScenarioBallots } = require(`${out}/data/defaultScenario.js`);
const { getDefaultIssueCount, clampCustomIssueCount, requiredRallyIssueCount, validateDefaultScenario, makeAnonymousClassCandidate } = require(`${out}/lib/scenarioValidation.js`);
const npc = candidates.filter(c => ['pippa','tika','bruno','luna','milo'].includes(c.id));
assert.equal(getDefaultIssueCount('little'), 5);
assert.equal(getDefaultIssueCount('trail'), 7);
assert.equal(getDefaultIssueCount('assembly'), 9);
assert.equal(clampCustomIssueCount(3), 5);
assert.equal(clampCustomIssueCount(13), 12);
assert.equal(requiredRallyIssueCount(9, 'assembly', 'Standard'), 7);
assert.equal(requiredRallyIssueCount(9, 'assembly', 'Full manifesto'), 9);
assert.equal(requiredRallyIssueCount(5, 'little', 'Short'), 5);
const validation = validateDefaultScenario(defaultScenarioBallots, npc);
assert.equal(validation.pluralityWinner, 'pippa');
assert.equal(validation.irvWinner, 'luna');
assert.equal(validation.approvalWinner, 'bruno');
assert.equal(validation.approvalTotals.bruno, 40);
assert.equal(validation.approvalTotals.luna, 35);
assert.ok(validation.approvalMargin >= 5 && validation.approvalMargin <= 10);
assert.ok(validation.viableCandidates >= 3);
const anon = makeAnonymousClassCandidate(1, studentTeamCandidates[0]);
assert.equal(anon.name, 'Anonymous Team 1');
console.log('Validation tests passed');
