import type { ElectionSettings, Polarization } from '../types/game';

const modes = ['Solo','Small group','Full class'] as const;
const candidateTypes = ['Animal NPC candidates','Student candidates','Student teams','Mixed mode'] as const;
const compareModes = ['Single voting system only','Run same election under multiple voting systems'] as const;
const tones = ['Friendly','Competitive','Debate-heavy'] as const;
const rallyLengths = ['Short','Standard','Full manifesto'] as const;
const strictness = ['Strict','Balanced','Generous'] as const;
const balances = ['Same winner across systems','Different winners across systems','Surprise close election','Runoff lesson','Approval compromise lesson','Equal strength','Asymmetric','Surprise outcome'] as const;
const privacy = ['Named candidates','Team names','Animal avatars','Anonymous ballots'] as const;

function Select<T extends string>({label,value,onChange,options}:{label:string;value:T;onChange:(value:T)=>void;options:readonly T[]}){return <label>{label}<select value={value} onChange={(e: any)=>onChange(e.target.value as T)}>{options.map(option=><option key={option}>{option}</option>)}</select></label>}

export function ElectionWorkshop({seed,setSeed,polarization,setPolarization,settings,setSettings,requiredIssueCount}:{seed:number;setSeed:(n:number)=>void;polarization:Polarization;setPolarization:(p:Polarization)=>void;settings:ElectionSettings;setSettings:(s:ElectionSettings)=>void;requiredIssueCount:number}){
 const update=<K extends keyof ElectionSettings>(key:K,value:ElectionSettings[K])=>setSettings({...settings,[key]:value});
 return <section className="panel"><p className="eyebrow">Election Workshop</p><h2>Tune the election</h2><div className="settings-grid"><label>Seed <input type="number" value={seed} onChange={(e: any)=>setSeed(Number(e.target.value)||1)}/></label><label>Polarization <select value={polarization} onChange={(e: any)=>setPolarization(e.target.value as Polarization)}>{['Low','Medium','High'].map(p=><option key={p}>{p}</option>)}</select></label><Select label="Mode" value={settings.mode} onChange={v=>update('mode',v)} options={modes}/><Select label="Candidate type" value={settings.candidateType} onChange={v=>update('candidateType',v)} options={candidateTypes}/><Select label="Compare systems" value={settings.compareMode} onChange={v=>update('compareMode',v)} options={compareModes}/><Select label="Campaign tone" value={settings.campaignTone} onChange={v=>update('campaignTone',v)} options={tones}/><Select label="Rally length" value={settings.rallyLength} onChange={v=>update('rallyLength',v)} options={rallyLengths}/><Select label="Approval strictness" value={settings.approvalStrictness} onChange={v=>update('approvalStrictness',v)} options={strictness}/><Select label="Candidate balance" value={settings.candidateBalance} onChange={v=>update('candidateBalance',v)} options={balances}/><Select label="Class privacy" value={settings.classPrivacy} onChange={v=>update('classPrivacy',v)} options={privacy}/><label><input type="checkbox" checked={settings.customIssueCount} onChange={(e: any)=>update('customIssueCount',e.target.checked)}/> Teacher custom issue count</label><label>Issue count <input type="number" min={5} max={12} disabled={!settings.customIssueCount} value={settings.issueCount} onChange={(e: any)=>update('issueCount',Math.max(5,Math.min(12,Number(e.target.value)||requiredIssueCount)))}/></label></div><p className="teacher">Current required issues: {requiredIssueCount}. Class Mode defaults to teams, animal avatars, and anonymous/team-friendly choices to avoid popularity contests.</p></section>}
